import {
  AlertCircle,
  Anchor,
  Archive,
  ArrowDownNarrowWide,
  ArrowUpNarrowWide,
  BadgeCheck,
  BadgeDollarSign,
  BadgePlus,
  BanknoteX,
  Bell,
  BellOff,
  BetweenVerticalStart,
  Bolt,
  BowArrow,
  Boxes,
  Building2,
  Calendar,
  ChartNoAxesGantt,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  Church,
  CircleCheckBig,
  CircleDashed,
  CircleDollarSign,
  CircleOff,
  CirclePercent,
  CircleX,
  ClipboardMinus,
  ClockFading,
  ContactRound,
  CreditCard,
  Crown,
  DiamondPlus,
  Dna,
  DollarSign,
  Eye,
  EyeOff,
  FileText,
  Folder,
  HandCoins,
  House,
  HousePlus,
  Info,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  ListFilterPlus,
  ListTree,
  Lock,
  LogIn,
  LogOut,
  Logs,
  Mail,
  MapIcon,
  MapPin,
  MapPinHouse,
  Menu,
  NotepadTextDashed,
  OctagonAlert,
  Paperclip,
  Pencil,
  Percent,
  Phone,
  Receipt,
  Search,
  Settings2,
  Shield,
  ShieldCheck,
  ShieldUser,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Signature,
  SlidersHorizontal,
  Split,
  Target,
  Telescope,
  Trash,
  TrendingUpDown,
  Truck,
  TruckElectric,
  Upload,
  UserRound,
  UserRoundCog,
  UserRoundPen,
  UserRoundPlus,
  UserRoundSearch,
  UserRoundX,
  UsersRound,
  UserX,
  Wallet,
  WalletMinimal,
  X,
} from 'lucide-react'

const icons = {
  'add-user': UserRoundPlus,
  address: MapPinHouse,
  alert: AlertCircle,
  anchor: Anchor,
  approved: CircleCheckBig,
  archive: Archive,
  attachment: Paperclip,
  backoffice: UserRoundCog,
  'bank-slit': BadgeDollarSign,
  'ban-user': UserRoundX,
  'bow-arrow': BowArrow,
  calendar: Calendar,
  cancellation: BanknoteX,
  cart: ShoppingCart,
  'cart-a': ShoppingBag,
  'cart-b': ShoppingBasket,
  church: Church,
  city: Building2,
  close: X,
  contract: NotepadTextDashed,
  config: Settings2,
  contact: ContactRound,
  company: Building2,
  crown: Crown,
  'credit-card': CreditCard,
  dashboard: Boxes,
  'dashboard-a': LayoutDashboard,
  'dashboard-b': LayoutGrid,
  delivery: Truck,
  'delivery-a': TruckElectric,
  document: FileText,
  dollar: DollarSign,
  done: CircleCheckBig,
  dna: Dna,
  edit: Pencil,
  'edit-user': UserRoundPen,
  enrollment: Signature,
  fee: CirclePercent,
  'first-page': ChevronFirst,
  filter: ListFilterPlus,
  folder: Folder,
  grant: ShieldCheck,
  'hide-password': EyeOff,
  home: House,
  idea: Lightbulb,
  info: Info,
  key: KeyRound,
  'last-page': ChevronLast,
  lead: DiamondPlus,
  'lead-company': BadgePlus,
  list: Logs,
  locate: MapPinHouse,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  map: MapIcon,
  'map-marker': MapPin,
  mission: Target,
  menu: Menu,
  'menu-a': ListTree,
  'menu-b': Logs,
  'menu-c': ChartNoAxesGantt,
  money: HandCoins,
  'next-page': ChevronRight,
  notification: Bell,
  'notification-off': BellOff,
  'order-by-asc': ArrowUpNarrowWide,
  'order-by-desc': ArrowDownNarrowWide,
  payment: CircleDollarSign,
  phone: Phone,
  pix: Receipt,
  'prev-page': ChevronLeft,
  pending: ClockFading,
  people: UsersRound,
  preferences: SlidersHorizontal,
  recused: CircleOff,
  report: ClipboardMinus,
  save: CircleCheckBig,
  search: Search,
  seal: BadgeCheck,
  settings: Bolt,
  signature: Signature,
  shield: Shield,
  'show-password': Eye,
  split: Split,
  'split-a': TrendingUpDown,
  tabs: BetweenVerticalStart,
  taxes: Percent,
  trash: Trash,
  unknown: OctagonAlert,
  user: UserRound,
  'user-config': UserRoundCog,
  'user-permission': ShieldUser,
  upload: Upload,
  values: Dna,
  vision: Telescope,
  wallet: Wallet,
  'wallet-a': WalletMinimal,
} as const

type Icons = keyof typeof icons

const getIconByName = (name: Icons) => {
  return icons[name] ?? CircleDashed
}

const Config = {
  getIconByName,
}

export type { Icons }
export default Config
export const IconConfig = Config
