import {
  Anchor,
  ArrowDownNarrowWide,
  ArrowUpNarrowWide,
  BadgeDollarSign,
  BetweenVerticalStart,
  BookUser,
  BowArrow,
  Building2,
  Calendar,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  CircleCheckBig,
  CircleDollarSign,
  CircleOff,
  ClockFading,
  ContactRound,
  CreditCard,
  Crown,
  DollarSign,
  Edit,
  Eye,
  EyeOff,
  ListFilterPlus,
  Logs,
  Mail,
  MapIcon,
  MapPin,
  MapPinHouse,
  Pencil,
  Phone,
  Pin,
  Receipt,
  Save,
  Search,
  Trash,
  UserRound,
  UserRoundCog,
  UserRoundPen,
  UserRoundPlus,
  X,
} from 'lucide-react'

const icons = {
  'add-user': UserRoundPlus,
  address: MapPinHouse,
  anchor: Anchor,
  approved: CircleCheckBig,
  'bank-slit': BadgeDollarSign,
  'bow-arrow': BowArrow,
  calendar: Calendar,
  contact: ContactRound,
  close: X,
  crown: Crown,
  'credit-card': CreditCard,
  city: Building2,
  dollar: DollarSign,
  done: CircleCheckBig,
  edit: Pencil,
  'edit-user': UserRoundPen,
  'first-page': ChevronFirst,
  filter: ListFilterPlus,
  'hide-password': EyeOff,
  'last-page': ChevronLast,
  list: Logs,
  locate: MapPinHouse,
  mail: Mail,
  map: MapIcon,
  'map-marker': MapPin,
  'next-page': ChevronRight,
  'order-by-asc': ArrowUpNarrowWide,
  'order-by-desc': ArrowDownNarrowWide,
  payment: CircleDollarSign,
  phone: Phone,
  pix: Receipt,
  'prev-page': ChevronLeft,
  pending: ClockFading,
  recused: CircleOff,
  save: CircleCheckBig,
  search: Search,
  'show-password': Eye,
  tabs: BetweenVerticalStart,
  trash: Trash,
  user: UserRound,
  'user-config': UserRoundCog,
} as const

type Icons = keyof typeof icons

const getIconByName = (name: Icons) => {
  return icons[name]
}

const Config = {
  getIconByName,
}

export type { Icons }
export default Config
export const IconConfig = Config
